version: '3.8'

services:
  controlador:
    build: ./controlador
    container_name: controlador-central
    ports:
      - "8080:8080"
    networks:
      - fabrica-net

  robo-soldagem:
    build: ./robo
    container_name: robo-soldagem
    command: java -cp target/classes org.example.RoboDistribuido SOLDAGEM controlador 8080
    depends_on:
      - controlador
    networks:
      - fabrica-net

  robo-pintura:
    build: ./robo
    container_name: robo-pintura
    command: java -cp target/classes org.example.RoboDistribuido PINTURA controlador 8080
    depends_on:
      - controlador
    networks:
      - fabrica-net

  robo-montagem:
    build: ./robo
    container_name: robo-montagem
    command: java -cp target/classes org.example.RoboDistribuido MONTAGEM controlador 8080
    depends_on:
      - controlador
    networks:
      - fabrica-net

  estoque:
    build: ./estoque
    container_name: gerenciador-estoque
    ports:
      - "8081:8081"
    networks:
      - fabrica-net

  monitor:
    build: ./monitor
    container_name: monitor-sistema
    ports:
      - "8082:8082"
    networks:
      - fabrica-net

networks:
  fabrica-net:
    driver: bridge