FROM openjdk:21-jdk-slim

# Instalar Maven
RUN apt-get update && apt-get install -y maven

WORKDIR /app

# Copiar arquivos do projeto
COPY ./src /app/src
COPY ./pom.xml /app/pom.xml

# Compilar o projeto com Maven
RUN mvn clean compile dependency:copy-dependencies

# Executar o monitor
CMD ["java", "-cp", "target/classes:target/dependency/*", "org.example.MonitorAvancado"]